// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc_dxIlK8vzWLJB45ZPw-Cv8XnFZ1-VL0',
    appId: '1:1070348317689:web:42abdacef9ad653b454328',
    messagingSenderId: '1070348317689',
    projectId: 'i-can-read-ecf5d',
    authDomain: 'i-can-read-ecf5d.firebaseapp.com',
    storageBucket: 'i-can-read-ecf5d.appspot.com',
    measurementId: 'G-BPFXFVWQL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa1i4UpHP0XUG2gZJflPoZFGrQoGBtfXU',
    appId: '1:1070348317689:android:adf8f99058f1c8b0454328',
    messagingSenderId: '1070348317689',
    projectId: 'i-can-read-ecf5d',
    storageBucket: 'i-can-read-ecf5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhdySPocCO1oduopl3s1aKjszrofw6rQI',
    appId: '1:1070348317689:ios:e48cf02d87e232d5454328',
    messagingSenderId: '1070348317689',
    projectId: 'i-can-read-ecf5d',
    storageBucket: 'i-can-read-ecf5d.appspot.com',
    iosClientId: '1070348317689-cdh2munvt6uf6s10jol3k8uq849gcuec.apps.googleusercontent.com',
    iosBundleId: 'com.example.iCanRead',
  );
}
